#!/bin/bash
ACTION=$1
THREADS=`lscpu | grep "Thread(s)" | awk '{print $4}'`
CPUS=`lscpu | grep "CPU(s):" | awk '{print $2}'`


if [ "$THREADS" -gt "1" ]; then
  echo "Hyperthreading is on with $THREADS per Core, total $CPUS cpus found"
fi

if [ "$ACTION" == "" ]; then
  echo "usage: $0 [ on | off ]"
  echo "use to turn hyperthreading in the cpu on or off"
  exit
fi

if [ "$ACTION" == "on" ]; then
  echo "on requested"
  for (( i=1; i<$CPUS; i=i+2 )) ; do
    echo turning on cpu$i;
    echo 1 > /sys/devices/system/cpu/cpu$i/online  
  done
  exit
fi

if [ "$ACTION" == "off" ]; then
  echo "off requested"
  for (( i=1; i<$CPUS; i=i+2 )) ; do
    echo turning off cpu$i;
    echo 0 > /sys/devices/system/cpu/cpu$i/online  
  done
  exit
fi

echo "option $ACTION is unknown"
echo "usage: $0 [ on | off ]"

# ref command
#echo 0 > /sys/devices/system/cpu/cpu3/online  
